--
-- seed.sql
--
-- THIS IS A COMMENT.
--
-- DEFINE YOUR SEED DATA HERE (INSERT DDLs)
--
-- e.g.
--
-- INSERT INTO users (email,firstname,lastname,organization,title,password) VALUES ('john@email.com','John','Doe','My Organization','CFO','password');
-- INSERT INTO users (email,firstname,lastname,organization,title,password) VALUES ('jane@email.com','Jane','Doe','My Organization','CEO','password');
-- INSERT INTO users (email,firstname,lastname,organization,title,password) VALUES ('jack@email.com','Jack','Doe','My Organization','CIO','password');
-- INSERT INTO users (email,firstname,lastname,organization,title,password) VALUES ('jill@email.com','Jill','Doe','Other Organization','CEO','password');
-- INSERT INTO users (email,firstname,lastname,organization,title,password) VALUES ('jenn@email.com','Jenn','Doe','Other Organization','CIO','password');
--
